elasticsearch:
  image: bashell/alpine-elasticsearch
  ports:
    - "9200:9200"

testrunner:
  image: sageone/elasticsearch_test_runner
  container_name: test_runner
  links:
    - elasticsearch
  volumes:
    - ../:/elastic_search_framework
