version: '2.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    # image: elasticsearch:5.6-alpine
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.type=single-node

    ports:
      - "9200:9200"

  testrunner:
    image: sage/elasticsearch_test_runner
    container_name: test_runner
    command: sh -c "apk add less; while true; do echo 'Container is running..'; sleep 5; done"
    environment:
      - ELASTIC_SEARCH_HOST=http://elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - ../:/elastic_search_framework
