name: RSpec
on:
  - push
  - pull_request
  - repository_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 5.6.0

      - name: Run tests
        env:
          ELASTIC_SEARCH_HOST: http://localhost
        run: bundle exec rspec
