name: RSpec
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.7', '3.2']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 1
          bundler-cache: true
        env:
          ImageOS: ubuntu18

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 6.8.17

      - name: Run tests
        env:
          ELASTIC_SEARCH_HOST: http://localhost
        run: bundle exec rspec
