name: RSpec
on:
  - push
  - pull_request
  - repository_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: elasticsearch
        ports:
          - 9200:9200

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true

      - name: Run tests
        env:
          ELASTIC_SEARCH_HOST: http://localhost
        run: bundle exec rspec
